# Generated by Django 2.2.16 on 2021-07-29 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 550817))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('phone_number', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Employed', 'Employed'), ('Laid Off', 'Laid Off'), ('Terminated', 'Terminated'), ('Vacation', 'Vacation')], max_length=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 553808))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('invoice', models.FileField(null=True, upload_to='static/invoices')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 553808))),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Company')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('appointment', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 554800))),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Company')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField()),
                ('file', models.FileField(blank=True, upload_to='static/revision')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('invoice', models.FileField(null=True, upload_to='static/merchant_invoices')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 555797))),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('manual', models.FileField(null=True, upload_to='static/manuals')),
                ('video', models.FileField(null=True, upload_to='static/videos')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 552807))),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(null=True, upload_to='static/machine_documents')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 17, 14, 30, 552807))),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeW2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w2_1099', models.FileField(blank=True, upload_to='')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_stub', models.FileField(blank=True, upload_to='')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
            ],
        ),
    ]
